/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */
export * from "./Erc20Factory";
export * from "./Erc20BurnableFactory";
export * from "./Erc20MintableFactory";
export * from "./Erc20MintableBurnableFactory";
export * from "./SimpleStorageFactory";
export * from "./SimpleStorage2Factory";
